package com.derun.webservice.client.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2016-11-22T09:42:32.272+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://service.wtmd.derun.com", name = "QuesListUpdateServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface QuesListUpdateServicePortType {

    @WebResult(name = "out", targetNamespace = "http://service.wtmd.derun.com")
    @RequestWrapper(localName = "loadQuesList", targetNamespace = "http://service.wtmd.derun.com", className = "com.derun.webservice.client.cxf.LoadQuesList")
    @WebMethod
    @ResponseWrapper(localName = "loadQuesListResponse", targetNamespace = "http://service.wtmd.derun.com", className = "com.derun.webservice.client.cxf.LoadQuesListResponse")
    public com.derun.webservice.client.cxf.QuesListUpdateResInfo loadQuesList(
        @WebParam(name = "in0", targetNamespace = "http://service.wtmd.derun.com")
        com.derun.webservice.client.cxf.QuesListUpdateReqInfo in0
    );
}
