
package com.derun.webservice.client.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2016-11-22T09:42:32.178+08:00
 * Generated source version: 2.6.0
 * 
 */
public final class QuesListUpdateServicePortType_QuesListUpdateServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.wtmd.derun.com", "QuesListUpdateService");

    private QuesListUpdateServicePortType_QuesListUpdateServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = QuesListUpdateService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QuesListUpdateService ss = new QuesListUpdateService(wsdlURL, SERVICE_NAME);
        QuesListUpdateServicePortType port = ss.getQuesListUpdateServiceHttpPort();  
        
        {
        System.out.println("Invoking loadQuesList...");
        com.derun.webservice.client.cxf.QuesListUpdateReqInfo _loadQuesList_in0 = null;
        com.derun.webservice.client.cxf.QuesListUpdateResInfo _loadQuesList__return = port.loadQuesList(_loadQuesList_in0);
        System.out.println("loadQuesList.result=" + _loadQuesList__return);


        }

        System.exit(0);
    }

}
